[2025-03-29 09:54:09.549] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 09:57:07.577] ERROR uncaughtException: Cannot read properties of undefined (reading 'sendLogError')
TypeError: Cannot read properties of undefined (reading 'sendLogError')
    at <anonymous> (/Users/will/dev/fintrack/packages/db/src/database.ts:29:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) TypeError: Cannot read properties of undefined (reading 'sendLogError')
    at <anonymous> (/Users/will/dev/fintrack/packages/db/src/database.ts:29:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-03-29 09:57:17.5717] ERROR uncaughtException: Cannot read properties of undefined (reading 'sendLogError')
TypeError: Cannot read properties of undefined (reading 'sendLogError')
    at <anonymous> (/Users/will/dev/fintrack/packages/db/src/database.ts:33:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) TypeError: Cannot read properties of undefined (reading 'sendLogError')
    at <anonymous> (/Users/will/dev/fintrack/packages/db/src/database.ts:33:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-03-29 09:57:21.5721] ERROR uncaughtException: makeLoggerProvider is not defined
ReferenceError: makeLoggerProvider is not defined
    at new Database (/Users/will/dev/fintrack/packages/db/src/database.ts:17:5)
    at Function.getInstance (/Users/will/dev/fintrack/packages/db/src/database.ts:21:27)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:8:29)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14) ReferenceError: makeLoggerProvider is not defined
    at new Database (/Users/will/dev/fintrack/packages/db/src/database.ts:17:5)
    at Function.getInstance (/Users/will/dev/fintrack/packages/db/src/database.ts:21:27)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:8:29)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
[2025-03-29 09:58:33.5833] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 09:58:33.5833] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:01:19.119] ERROR Starting server... Starting server... Error: Starting server...
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:13:12)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:21:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:21:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at cjsLoader (node:internal/modules/esm/translators:263:5)
[2025-03-29 10:01:23.123] ERROR Starting server... Starting server... Error: Starting server...
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:13:12)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:21:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:21:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at cjsLoader (node:internal/modules/esm/translators:263:5)
[2025-03-29 10:01:34.134] ERROR Starting server...
[2025-03-29 10:02:02.22] ERROR uncaughtException: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:37:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186) FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:37:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
[2025-03-29 10:02:02.22] ERROR uncaughtException: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:37:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186) FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:37:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
[2025-03-29 10:02:07.27] ERROR uncaughtException: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186) FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
[2025-03-29 10:02:07.27] ERROR uncaughtException: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186) FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
[2025-03-29 10:02:07.27] ERROR uncaughtException: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186) FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
[2025-03-29 10:02:12.212] ERROR uncaughtException: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186) FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
[2025-03-29 10:02:12.212] ERROR uncaughtException: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186) FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
[2025-03-29 10:02:12.212] ERROR uncaughtException: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186) FastifyError: Invalid logger object provided. The logger instance should have these functions(s): 'fatal,trace'.
    at FastifyError (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+error@4.1.0/node_modules/@fastify/error/index.js:18:14)
    at validateLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:71:11)
    at createLogger (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/logger-factory.js:99:7)
    at fastify (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/fastify.js:139:33)
    at new FastifyFramework (/Users/will/dev/fintrack/apps/core-api/src/http/fastify-app.ts:39:16)
    at start (/Users/will/dev/fintrack/apps/core-api/src/server.ts:10:18)
    at <anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:1)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/server.ts:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object.transformer (/Users/will/dev/fintrack/node_modules/.pnpm/tsx@4.19.3/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
[2025-03-29 10:03:36.336] ERROR SignInUserRestController.handle() error Cannot read properties of undefined (reading 'credentials') TypeError: Cannot read properties of undefined (reading 'credentials')
    at SignInUserRestController.performOperation (/Users/will/dev/fintrack/apps/core-api/src/controllers/rest/users/sign-in-user.rest-controller.ts:55:46)
    at SignInUserRestController.handle (/Users/will/dev/fintrack/packages/domain/dist/chunk-JDOLQ3D6.js:51:33)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:17:39)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
[2025-03-29 10:03:36.336] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:03:36.336] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:03:36.336] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:03:36.336] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:03:36.336] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:03:36.336] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:03:36.336] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:32:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:07:44.744] ERROR SignInUserRestController.handle() error Cannot read properties of undefined (reading 'credentials') TypeError: Cannot read properties of undefined (reading 'credentials')
    at SignInUserRestController.performOperation (/Users/will/dev/fintrack/apps/core-api/src/controllers/rest/users/sign-in-user.rest-controller.ts:55:46)
    at SignInUserRestController.handle (/Users/will/dev/fintrack/packages/domain/dist/chunk-JDOLQ3D6.js:51:33)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:17:39)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
[2025-03-29 10:07:44.744] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:07:44.744] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:07:44.744] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:07:44.744] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:07:44.744] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:07:44.744] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:07:44.744] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:09:02.92] ERROR SignInUserRestController.handle() error Cannot read properties of undefined (reading 'credentials') TypeError: Cannot read properties of undefined (reading 'credentials')
    at SignInUserRestController.performOperation (/Users/will/dev/fintrack/apps/core-api/src/controllers/rest/users/sign-in-user.rest-controller.ts:55:46)
    at SignInUserRestController.handle (/Users/will/dev/fintrack/packages/domain/dist/chunk-JDOLQ3D6.js:51:33)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:17:39)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
[2025-03-29 10:09:02.92] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:09:02.92] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:09:02.92] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:09:02.92] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:09:02.92] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:09:02.92] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:09:02.92] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:14:12.1412] ERROR SignInUserRestController.handle() error Cannot read properties of undefined (reading 'credentials') TypeError: Cannot read properties of undefined (reading 'credentials')
    at SignInUserRestController.performOperation (/Users/will/dev/fintrack/apps/core-api/src/controllers/rest/users/sign-in-user.rest-controller.ts:56:46)
    at SignInUserRestController.handle (/Users/will/dev/fintrack/packages/domain/dist/chunk-JDOLQ3D6.js:51:33)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:17:39)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
[2025-03-29 10:14:12.1412] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:14:12.1412] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:14:12.1412] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:14:12.1412] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:14:12.1412] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:14:12.1412] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:14:12.1412] ERROR uncaughtException: the request is not multipart
FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9 FastifyError: the request is not multipart
    at _Request.handleMultipart (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:212:13)
    at _Request.getMultipartFile [as file] (/Users/will/dev/fintrack/node_modules/.pnpm/@fastify+multipart@9.0.3/node_modules/@fastify/multipart/index.js:513:42)
    at adaptRequest (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:33:25)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:16:27)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
[2025-03-29 10:16:53.1653] ERROR Error in users repository in validate email method. Error in external lib name: prisma.
[2025-03-29 10:16:53.1653] ERROR SignInUserRestController.handle() error
[2025-03-29 10:21:28.2128] ERROR Error in users repository in validate email method. Error in external lib name: prisma.
[2025-03-29 10:21:28.2128] ERROR SignInUserRestController.handle() error
[2025-03-29 10:21:55.2155] ERROR Error in users repository in validate email method. Error in external lib name: prisma.
[2025-03-29 10:21:55.2155] ERROR SignInUserRestController.handle() error
[2025-03-29 10:24:11.2411] ERROR SignInUserRestController.handle() error
[2025-03-29 10:24:12.2412] ERROR SignInUserRestController.handle() error
[2025-03-29 10:52:50.5250] ERROR uncaughtException: (0 , import_sign_up_user.signUpUserRoute) is not a function
TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[2025-03-29 10:52:50.5250] ERROR uncaughtException: (0 , import_sign_up_user.signUpUserRoute) is not a function
TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[2025-03-29 10:52:50.5250] ERROR uncaughtException: (0 , import_sign_up_user.signUpUserRoute) is not a function
TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[2025-03-29 10:52:50.5250] ERROR uncaughtException: (0 , import_sign_up_user.signUpUserRoute) is not a function
TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[2025-03-29 10:52:50.5250] ERROR uncaughtException: (0 , import_sign_up_user.signUpUserRoute) is not a function
TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[2025-03-29 10:52:50.5250] ERROR uncaughtException: (0 , import_sign_up_user.signUpUserRoute) is not a function
TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[2025-03-29 10:52:50.5250] ERROR uncaughtException: (0 , import_sign_up_user.signUpUserRoute) is not a function
TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) TypeError: (0 , import_sign_up_user.signUpUserRoute) is not a function
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:8:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[2025-03-29 10:54:50.5450] ERROR SignInUserRestController.handle() error Cannot destructure property 'email' of 'request.body.credentials' as it is undefined. TypeError: Cannot destructure property 'email' of 'request.body.credentials' as it is undefined.
    at SignInUserRestController.performOperation (/Users/will/dev/fintrack/apps/core-api/src/controllers/rest/users/sign-in-user.rest-controller.ts:56:13)
    at SignInUserRestController.handle (/Users/will/dev/fintrack/packages/domain/dist/chunk-JDOLQ3D6.js:51:33)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:17:39)
    at preHandlerCallbackInner (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:161:24)
    at preHandlerCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:129:5)
    at validationCompleted (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:119:5)
    at preValidationCallback (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:96:5)
    at handler (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/handleRequest.js:73:7)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/contentTypeParser.js:214:9
    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
[2025-03-29 10:55:58.5558] ERROR Unhandled error: Response doesn't match the schema Response doesn't match the schema FastifyError: Response doesn't match the schema
    at new ResponseSerializationError (/Users/will/dev/fintrack/node_modules/.pnpm/fastify-type-provider-zod@4.0.2_fastify@5.2.2_zod@3.24.2/node_modules/fastify-type-provider-zod/dist/src/errors.js:11:9)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify-type-provider-zod@4.0.2_fastify@5.2.2_zod@3.24.2/node_modules/fastify-type-provider-zod/dist/src/core.js:89:15
    at serialize (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:924:12)
    at preSerializationHookEnd (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:504:17)
    at preSerializationHook (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:488:5)
    at Reply.send (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:204:7)
    at adaptResponse (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:66:41)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:18:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-03-29 10:56:41.5641] ERROR SignUpUserRestController.handle() error
[2025-03-29 10:56:45.5645] ERROR SignInUserRestController.handle() error
[2025-03-29 10:56:53.5653] ERROR Unhandled error: Response doesn't match the schema Response doesn't match the schema FastifyError: Response doesn't match the schema
    at new ResponseSerializationError (/Users/will/dev/fintrack/node_modules/.pnpm/fastify-type-provider-zod@4.0.2_fastify@5.2.2_zod@3.24.2/node_modules/fastify-type-provider-zod/dist/src/errors.js:11:9)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify-type-provider-zod@4.0.2_fastify@5.2.2_zod@3.24.2/node_modules/fastify-type-provider-zod/dist/src/core.js:89:15
    at serialize (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:924:12)
    at preSerializationHookEnd (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:504:17)
    at preSerializationHook (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:488:5)
    at Reply.send (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:204:7)
    at adaptResponse (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:66:41)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:18:13)
[2025-03-29 10:57:18.5718] ERROR Unhandled error: Response doesn't match the schema Response doesn't match the schema FastifyError: Response doesn't match the schema
    at new ResponseSerializationError (/Users/will/dev/fintrack/node_modules/.pnpm/fastify-type-provider-zod@4.0.2_fastify@5.2.2_zod@3.24.2/node_modules/fastify-type-provider-zod/dist/src/errors.js:11:9)
    at /Users/will/dev/fintrack/node_modules/.pnpm/fastify-type-provider-zod@4.0.2_fastify@5.2.2_zod@3.24.2/node_modules/fastify-type-provider-zod/dist/src/core.js:89:15
    at serialize (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:924:12)
    at preSerializationHookEnd (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:504:17)
    at preSerializationHook (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:488:5)
    at Reply.send (/Users/will/dev/fintrack/node_modules/.pnpm/fastify@5.2.2/node_modules/fastify/lib/reply.js:204:7)
    at adaptResponse (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:66:41)
    at Object.<anonymous> (/Users/will/dev/fintrack/apps/core-api/src/http/fastify.adapter.ts:18:13)
[2025-03-29 10:59:34.5934] ERROR SignInUserRestController.handle() error
[2025-03-29 11:00:12.012] ERROR uncaughtException: HttpStatusCode is not defined
ReferenceError: HttpStatusCode is not defined
    at signInUserRoute (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/sign-in-user.route.ts:26:12)
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:7:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) ReferenceError: HttpStatusCode is not defined
    at signInUserRoute (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/sign-in-user.route.ts:26:12)
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:7:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[2025-03-29 11:00:12.012] ERROR uncaughtException: HttpStatusCode is not defined
ReferenceError: HttpStatusCode is not defined
    at signInUserRoute (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/sign-in-user.route.ts:26:12)
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:7:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) ReferenceError: HttpStatusCode is not defined
    at signInUserRoute (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/sign-in-user.route.ts:26:12)
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:7:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[2025-03-29 11:00:14.014] ERROR uncaughtException: HttpStatusCode is not defined
ReferenceError: HttpStatusCode is not defined
    at signInUserRoute (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/sign-in-user.route.ts:26:12)
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:7:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) ReferenceError: HttpStatusCode is not defined
    at signInUserRoute (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/sign-in-user.route.ts:26:12)
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:7:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[2025-03-29 11:00:14.014] ERROR uncaughtException: HttpStatusCode is not defined
ReferenceError: HttpStatusCode is not defined
    at signInUserRoute (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/sign-in-user.route.ts:26:12)
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:7:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) ReferenceError: HttpStatusCode is not defined
    at signInUserRoute (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/sign-in-user.route.ts:26:12)
    at usersRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/users/_users-routes.ts:7:3)
    at fastifyRoutes (/Users/will/dev/fintrack/apps/core-api/src/http/routes/fastify-routes.ts:6:3)
    at Plugin.exec (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/lib/plugin.js:125:28)
    at Boot._loadPlugin (/Users/will/dev/fintrack/node_modules/.pnpm/avvio@9.1.0/node_modules/avvio/boot.js:432:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
